=== dheraclio/dependometer/dependometer-cpp-1.2.7/src/test/test-dependencies/testconfig.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT testmetrics (pagemetrics+) >

<!ELEMENT pagemetrics (scanfile,metric*,verifytext*) >

<!ELEMENT metric (name|tablename|value)* >

<!ELEMENT name (#PCDATA) >

<!ELEMENT scanfile (#PCDATA) >

<!ELEMENT tablename (#PCDATA) >

<!ELEMENT value (#PCDATA) >

<!ELEMENT verifytext (#PCDATA) >

=== dheraclio/dependometer/dependometer-cpp/src/test/test-dependencies/abstractness/testconfig.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE testmetrics SYSTEM "../testconfig.dtd">

<testmetrics>

   <pagemetrics>
   
		<scanfile>project.html</scanfile>
	
		<metric>
	 	 <name>number of components</name>
	 	 <value>3</value>
		</metric>
	</pagemetrics>	
		
   <pagemetrics>
   
		<scanfile>compilation-unit-metrics.html</scanfile>
	
		<metric>
	 	  <tablename>number of abstract types (Na)</tablename>
	 	  <name>CSVFormat.cpp</name>
	 	  <value>0</value>
		</metric>
	    <metric>
	 	  <tablename>number of abstract types (Na)</tablename>
	 	  <name>XMLFormat.cpp</name>
	 	  <value>0</value>
		</metric>
		<metric>
	 	  <tablename>number of abstract types (Na)</tablename>
	 	  <name>BaseFormat.cpp</name>
	 	  <value>1</value>
		</metric>
		
		<metric>
	 	  <tablename>number of concrete types</tablename>
	 	  <name>CSVFormat.cpp</name>
	 	  <value>1</value>
		</metric>
		
		<metric>
	 	  <tablename>number of concrete types</tablename>
	 	  <name>XMLFormat.cpp</name>
	 	  <value>1</value>
		</metric>
 	
 	    <metric>
	 	  <tablename>number of concrete types</tablename>
	 	  <name>BaseFormat.cpp</name>
	 	  <value>0</value>
		</metric>
		
 	</pagemetrics>

 	
</testmetrics>

=== dheraclio/dependometer/dependometer-cpp/src/test/test-dependencies/acd_cyclic/testconfig.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE testmetrics SYSTEM "../testconfig.dtd">

<testmetrics>

   <pagemetrics>
   
		<scanfile>project.html</scanfile>
	
		<metric>
	 	 <name>number of components</name>
	 	 <value>6</value>
		</metric>
	
		<metric>
	 	 <name>cumulative component dependency (CCD)</name>
	 	 <value>26</value>
		</metric>
	
		<metric>
	 	 <name>average component dependency (ACD)</name>
	 	 <value>4.33</value>
		</metric>
 	
 	</pagemetrics>
 	
 	<pagemetrics>
   
		<scanfile>compilation-unit-levels.html</scanfile>
	
		<verifytext>compilation-units on level 1 (2)</verifytext>
		
 	</pagemetrics>
 	
 	<pagemetrics>
   
		<scanfile>type-levels.html</scanfile>
	
		<verifytext>types on level 1 (2)</verifytext>
		
 	</pagemetrics>
 	
 	
</testmetrics>

=== dheraclio/dependometer/dependometer-cpp-1.2.7/src/test/test-dependencies/coupling/testconfig.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE testmetrics SYSTEM "../testconfig.dtd">

<testmetrics>

   <pagemetrics>
   
		<scanfile>project.html</scanfile>
	
		<metric>
	 	 <name>number of components</name>
	 	 <value>3</value>
		</metric>
 	
 	</pagemetrics>
 	
 	<pagemetrics>
   
		<scanfile>package-metrics.html</scanfile>
	
		<metric>
		 <tablename>relational cohesion (RC)</tablename>
	 	 <name>geometry</name>
	 	 <value>0.66</value>
		</metric>
 	
 	    <metric>
		 <tablename>number of types (Nc)</tablename>
	 	 <name>geometry</name>
	 	 <value>3</value>
		</metric>
		
		<metric>
		 <tablename>number of internal type relations</tablename>
	 	 <name>geometry</name>
	 	 <value>2</value>
		</metric>
		
 	</pagemetrics>
 	
</testmetrics>

=== dheraclio/dependometer/dependometer-cpp-1.2.7/src/test/test-dependencies/packages/testconfig.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE testmetrics SYSTEM "../testconfig.dtd">

<testmetrics>

   <pagemetrics>
   
		<scanfile>project.html</scanfile>
	
		<metric>
	 	 <name>number of components</name>
	 	 <value>7</value>
		</metric>
 	
 	</pagemetrics>
 	
 	<pagemetrics>
   
		<scanfile>compilation-unit-levels.html</scanfile>
	
		<verifytext>compilation-units on level 1 (4)</verifytext>
		<verifytext>compilation-units on level 2 (2)</verifytext>
		<verifytext>compilation-units on level 3 (1)</verifytext>
	
 	</pagemetrics>
 	
 	<pagemetrics>
   
		<scanfile>package-levels.html</scanfile>
	
		<verifytext>packages on level 1 (1)</verifytext>
		<verifytext>packages on level 2 (1)</verifytext>
		<verifytext>packages on level 3 (1)</verifytext>
	
 	</pagemetrics>
 	
 	<pagemetrics>
   
		<scanfile>type-levels.html</scanfile>
	
		<verifytext>types on level 1 (4)</verifytext>
		<verifytext>types on level 2 (2)</verifytext>
		<verifytext>types on level 3 (1)</verifytext>
	
 	</pagemetrics>
 	
 	<pagemetrics>
   
		<scanfile>package-metrics.html</scanfile>
	
		<metric>
		 <tablename>afferent (incoming) coupling (Ca)</tablename>
	 	 <name>level1.nslevel1</name>
	 	 <value>2</value>
		</metric>
 	
 		<metric>
		 <tablename>afferent (incoming) coupling (Ca)</tablename>
	 	 <name>level2.nslevel2</name>
	 	 <value>1</value>
		</metric>
		
		<metric>
		 <tablename>afferent (incoming) coupling (Ca)</tablename>
	 	 <name>level3.nslevel3</name>
	 	 <value>0</value>
		</metric>
		
 	    <metric>
		 <tablename>efferent (outgoing) coupling (Ce)</tablename>
	 	 <name>level1.nslevel1</name>
	 	 <value>0</value>
		</metric>
		
		<metric>
		 <tablename>efferent (outgoing) coupling (Ce)</tablename>
	 	 <name>level2.nslevel2</name>
	 	 <value>4</value>
		</metric>
		
		<metric>
		 <tablename>efferent (outgoing) coupling (Ce)</tablename>
	 	 <name>level3.nslevel3</name>
	 	 <value>2</value>
		</metric>
		
		<metric>
		 <tablename>instability (I)</tablename>
	 	 <name>level1.nslevel1</name>
	 	 <value>0.0</value>
		</metric>
		
		<metric>
		 <tablename>instability (I)</tablename>
	 	 <name>level2.nslevel2</name>
	 	 <value>0.8</value>
		</metric>
		
		<metric>
		 <tablename>instability (I)</tablename>
	 	 <name>level3.nslevel3</name>
	 	 <value>1.0</value>
		</metric>
		
 	</pagemetrics>
 	
</testmetrics>

=== dheraclio/dependometer/dependometer-java/src/test/test-dependencies/exception/testconfig.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE testmetrics SYSTEM "../testconfig.dtd">

<testmetrics> <!-- see dependometer-cpp for more examples -->
	<pagemetrics>
		<scanfile>project.html</scanfile>
		<metric>
			<name>number of project internal types</name>
			<value>4</value>
		</metric>
	</pagemetrics>
	
	<pagemetrics>

		<scanfile>type-metrics.html</scanfile>

		<!-- check type dependencies related to annotations -->
		<metric>
			<tablename>number of outgoing dependencies</tablename>
			<name>default.Invoker</name>
			<value>2</value>
		</metric>

		<metric>
			<tablename>number of outgoing dependencies</tablename>
			<name>default.ExceptionThrower</name>
			<value>2</value>
		</metric>

		<metric>
			<tablename>number of outgoing dependencies</tablename>
			<name>default.UncheckedException</name>
			<value>0</value>
		</metric>

		<metric>
			<tablename>number of outgoing dependencies</tablename>
			<name>default.CheckedException</name>
			<value>0</value>
		</metric>

	</pagemetrics>
	
</testmetrics>

=== dheraclio/dependometer/dependometer-java/src/test/test-dependencies/inlineable/testconfig.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE testmetrics SYSTEM "../testconfig.dtd">

<testmetrics> <!-- see dependometer-cpp for more examples -->
	<pagemetrics>
		<scanfile>project.html</scanfile>
		<metric>
			<name>number of project internal types</name>
			<value>5</value>
		</metric>
	</pagemetrics>

	<pagemetrics>

		<scanfile>type-metrics.html</scanfile>

		<!-- check type dependencies related to annotations -->
		<metric>
			<tablename>number of outgoing dependencies</tablename>
			<name>inlineable0.ClassA</name>
			<value>2</value>
		</metric>

		<metric>
			<tablename>number of outgoing dependencies</tablename>
			<name>inlineable1.ClassF</name>
			<value>0</value>
		</metric>
	</pagemetrics>
</testmetrics>

=== dheraclio/dependometer/dependometer-java/src/test/test-dependencies/inheritance/testconfig.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE testmetrics SYSTEM "../testconfig.dtd">

<testmetrics> <!-- see dependometer-cpp for more examples -->
	<pagemetrics>
		<scanfile>project.html</scanfile>
		<metric>
			<name>number of project internal types</name>
			<value>3</value>
		</metric>
		<!-- inheritance metrics -->
		<metric>
			<name>max depth of type inheritance</name>
			<value>1</value>
		</metric>
	</pagemetrics>
</testmetrics>

=== dheraclio/dependometer/dependometer-java/src/test/test-dependencies/ccd/testconfig.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE testmetrics SYSTEM "../testconfig.dtd">

<testmetrics> <!-- see dependometer-cpp for more examples -->
	<pagemetrics>
		<scanfile>project.html</scanfile>

		<!-- checking CCD values -->
		<metric>
			<name>cumulative component dependency (CCD)</name>
			<value>20</value>
		</metric>

		<metric>
			<name>cumulative component dependency for balanced binary tree</name>
			<value>17</value>
		</metric>

		<metric>
			<name>cumulative component dependency for cyclically dependent graph</name>
			<value>49</value>
		</metric>
	</pagemetrics>

</testmetrics>
