=== dheraclio/dependometer/dependometer-cpp-1.2.7/src/test/test-dependencies/testconfig.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT testmetrics (pagemetrics+) >

<!ELEMENT pagemetrics (scanfile,metric*,verifytext*) >

<!ELEMENT metric (name|tablename|value)* >

<!ELEMENT name (#PCDATA) >

<!ELEMENT scanfile (#PCDATA) >

<!ELEMENT tablename (#PCDATA) >

<!ELEMENT value (#PCDATA) >

<!ELEMENT verifytext (#PCDATA) >

=== dheraclio/dependometer/dependometer-java-1.2.7/src/test/test-dependencies/annotations/testconfig.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE testmetrics SYSTEM "../testconfig.dtd">

<testmetrics> <!-- see dependometer-cpp for more examples -->
	<pagemetrics>
		<scanfile>project.html</scanfile>
		<metric>
			<name>number of project internal types</name>
			<value>14</value>
		</metric>
	</pagemetrics>

	<pagemetrics>

		<scanfile>type-metrics.html</scanfile>

		<!-- check type dependencies related to annotations -->
		<metric>
			<tablename>number of outgoing dependencies</tablename>
			<name>annotations.one.Type</name>
			<value>4</value>
		</metric>

		<metric>
			<tablename>number of outgoing dependencies</tablename>
			<name>annotations.one.Car</name>
			<value>3</value>
		</metric>

		<metric>
			<tablename>number of outgoing dependencies</tablename>
			<name>annotations.two.Motorbike</name>
			<value>3</value>
		</metric>

		<metric>
			<tablename>number of outgoing dependencies</tablename>
			<name>annotations.two.Trike</name>
			<value>3</value>
		</metric>

		<metric>
			<tablename>number of outgoing dependencies</tablename>
			<name>annotations.one.MCars</name>
			<value>2</value>
		</metric>

		<metric>
			<tablename>number of outgoing dependencies</tablename>
			<name>annotations.one.Nice</name>
			<value>2</value>
		</metric>

		<metric>
			<tablename>number of outgoing dependencies</tablename>
			<name>annotations.one.Type$SpecialType</name>
			<value>2</value>
		</metric>

		<metric>
			<tablename>number of outgoing dependencies</tablename>
			<name>annotations.one.Type$SubType</name>
			<value>2</value>
		</metric>

		<metric>
			<tablename>number of outgoing dependencies</tablename>
			<name>annotations.one.Agile</name>
			<value>1</value>
		</metric>

		<metric>
			<tablename>number of outgoing dependencies</tablename>
			<name>annotations.one.Fast</name>
			<value>1</value>
		</metric>

		<metric>
			<tablename>number of outgoing dependencies</tablename>
			<name>annotations.one.Joy</name>
			<value>1</value>
		</metric>

		<metric>
			<tablename>number of outgoing dependencies</tablename>
			<name>annotations.one.DrivingPleasure</name>
			<value>0</value>
		</metric>

		<metric>
			<tablename>number of outgoing dependencies</tablename>
			<name>annotations.one.Type$DrivingPleasure</name>
			<value>0</value>
		</metric>

		<metric>
			<tablename>number of outgoing dependencies</tablename>
			<name>annotations.two.Trike$Inner</name>
			<value>0</value>
		</metric>

	</pagemetrics>
</testmetrics>

=== dheraclio/dependometer/dependometer-cpp-1.2.7/src/test/test-dependencies/ccd_tree/testconfig.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE testmetrics SYSTEM "../testconfig.dtd">

<testmetrics>

   <pagemetrics>
   
		<scanfile>project.html</scanfile>
	
		<metric>
	 	 <name>number of components</name>
	 	 <value>7</value>
		</metric>
	
		<metric>
	 	 <name>cumulative component dependency (CCD)</name>
	 	 <value>17</value>
		</metric>
	
		<metric>
	 	 <name>cumulative component dependency for balanced binary tree</name>
	 	 <value>17</value>
		</metric>
		
		<metric>
	 	 <name>cumulative component dependency for cyclically dependent graph</name>
	 	 <value>49</value>
		</metric>
 	
 	</pagemetrics>
 	
 	<pagemetrics>
   
		<scanfile>compilation-unit-levels.html</scanfile>
	
		<verifytext>compilation-units on level 1 (4)</verifytext>
		<verifytext>compilation-units on level 2 (2)</verifytext>
		<verifytext>compilation-units on level 3 (1)</verifytext>
	
 	</pagemetrics>
 	
 	<pagemetrics>
   
		<scanfile>package-levels.html</scanfile>
	
		<verifytext>packages on level 1 (1)</verifytext>
		<verifytext>packages on level 2 (2)</verifytext> <!-- TODO: I (Uli) replaced (1) by (2) - this should be checked for correctness -->
		<verifytext>packages on level 3 (1)</verifytext>
	
 	</pagemetrics>
 	
 	<pagemetrics>
   
		<scanfile>type-levels.html</scanfile>
	
		<verifytext>types on level 1 (4)</verifytext>
		<verifytext>types on level 2 (2)</verifytext>
		<verifytext>types on level 3 (1)</verifytext>
	
 	</pagemetrics>
 	
 	
</testmetrics>

=== dheraclio/dependometer/dependometer-java/src/test/test-dependencies/cycle/testconfig.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE testmetrics SYSTEM "../testconfig.dtd">

<testmetrics> <!-- see dependometer-cpp for more examples -->
	<pagemetrics>

		<scanfile>project.html</scanfile>

		<!-- check for cycles -->
		<metric>
			<name>cycles exist between project internal types</name>
			<value>true</value>
		</metric>

		<metric>
			<name>cycles exist between project internal compilation units</name>
			<value>true</value>
		</metric>

		<metric>
			<name>cycles exist between project internal packages</name>
			<value>true</value>
		</metric>

		<metric>
			<name>cycles exist between project internal subsystems</name>
			<value>! not analyzed !</value>
		</metric>

		<metric>
			<name>cycles exist between project internal vertical slices</name>
			<value>! not analyzed !</value>
		</metric>

		<metric>
			<name>cycles exist between project internal layers</name>
			<value>! not analyzed !</value>
		</metric>

	</pagemetrics>

</testmetrics>

=== dheraclio/dependometer/dependometer-cpp/src/test/test-dependencies/distance/testconfig.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE testmetrics SYSTEM "../testconfig.dtd">

<testmetrics>

   <pagemetrics>
   
		<scanfile>project.html</scanfile>
	
		<metric>
	 	 <name>number of components</name>
	 	 <value>4</value>
		</metric>
	
 	</pagemetrics>
 	
 	
 	<pagemetrics>
   
		<scanfile>package-metrics.html</scanfile>
	
		<metric>
		 <tablename>afferent (incoming) coupling (Ca)</tablename>
	 	 <name>base</name>
	 	 <value>2</value>
		</metric>
 	
 		<metric>
		 <tablename>afferent (incoming) coupling (Ca)</tablename>
	 	 <name>formats</name>
	 	 <value>0</value>
		</metric>
		
 	    <metric>
		 <tablename>efferent (outgoing) coupling (Ce)</tablename>
	 	 <name>base</name>
	 	 <value>0</value>
		</metric>
		
		<metric>
		 <tablename>efferent (outgoing) coupling (Ce)</tablename>
	 	 <name>formats</name>
	 	 <value>1</value>
		</metric>
		
		<metric>
		 <tablename>instability (I)</tablename>
	 	 <name>base</name>
	 	 <value>0.0</value>
		</metric>
		
		<metric>
		 <tablename>instability (I)</tablename>
	 	 <name>formats</name>
	 	 <value>1.0</value>
		</metric>
		
		<metric>
		 <tablename>distance (D)</tablename>
	 	 <name>base</name>
	 	 <value>-0.5</value>
		</metric>
		
		<metric>
		 <tablename>distance (D)</tablename>
	 	 <name>formats</name>
	 	 <value>0.0</value>
		</metric>
		
		<!-- NOT SUPPORTED
		
		<metric>
		 <tablename>number of abstract types (Na)</tablename>
	 	 <name>base</name>
	 	 <value>1</value>
		</metric>
		
		-->
		
		<metric>
		 <tablename>number of abstract types (Na)</tablename>
	 	 <name>formats</name>
	 	 <value>0</value>
		</metric>
		
	  <!-- NOT SUPPORTED
	   <metric>
		 <tablename>number of types (Nc)</tablename>
	 	 <name>base</name>
	 	 <value>1</value>
		</metric>
		-->
		<metric>
		 <tablename>number of types (Nc)</tablename>
	 	 <name>formats</name>
	 	 <value>2</value>
		</metric>
		
 	</pagemetrics>
 	
</testmetrics>

=== dheraclio/dependometer/dependometer-cpp-1.2.7/src/test/test-dependencies/layers/testconfig.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE testmetrics SYSTEM "../testconfig.dtd">

<testmetrics>

   <pagemetrics>
   
		<scanfile>project.html</scanfile>
	
		<metric>
	 	 <name>number of components</name>
	 	 <value>8</value>
		</metric>
	
		<metric>
	 	 <name>number of not implemented subsystems</name>
	 	 <value>2</value>
		</metric>
 	
 	</pagemetrics>
 	
 	
</testmetrics>

=== dheraclio/dependometer/dependometer-java/src/test/test-dependencies/architecture/testconfig.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE testmetrics SYSTEM "../testconfig.dtd">

<testmetrics> <!-- see dependometer-cpp for more examples -->
	<pagemetrics>
		<scanfile>project.html</scanfile>
		<metric>
			<name>number of project internal types</name>
			<value>11</value>
		</metric>

		<metric>
			<name>number of project internal compilation units</name>
			<value>10</value>
		</metric>

		<metric>
			<name>number of project internal packages</name>
			<value>6</value>
		</metric>

		<metric>
			<name>number of project internal subsystems</name>
			<value>5</value>
		</metric>

		<metric>
			<name>number of project internal layers</name>
			<value>3</value>
		</metric>

		<metric>
			<name>number of project internal vertical slices</name>
			<value>! not analyzed !</value>
		</metric>

		<metric>
			<name>number of project external types</name>
			<value>1</value>
		</metric>

		<metric>
			<name>number of project external compilation units</name>
			<value>1</value>
		</metric>

		<metric>
			<name>number of project external packages</name>
			<value>1</value>
		</metric>

		<metric>
			<name>number of project external subsystems</name>
			<value>1</value>
		</metric>

		<metric>
			<name>number of project external layers</name>
			<value>1</value>
		</metric>

		<metric>
			<name>number of forbidden outgoing compilation unit dependencies</name>
			<value>12</value>
		</metric>

		<metric>
			<name>number of forbidden outgoing type dependencies</name>
			<value>12</value>
		</metric>

		<metric>
			<name>number of forbidden outgoing package dependencies</name>
			<value>9</value>
		</metric>

		<metric>
			<name>number of forbidden outgoing subsystem dependencies</name>
			<value>7</value>
		</metric>

		<metric>
			<name>number of forbidden outgoing layer dependencies</name>
			<value>2</value>
		</metric>
	</pagemetrics>

	<!-- layers -->
	<pagemetrics>
		<scanfile>layer-metrics.html</scanfile>

		<metric>
			<tablename>number of components</tablename>
			<name>model</name>
			<value>8</value>
		</metric>

		<metric>
			<tablename>number of components</tablename>
			<name>application</name>
			<value>1</value>
		</metric>

		<metric>
			<tablename>number of components</tablename>
			<name>persistence</name>
			<value>1</value>
		</metric>

		<metric>
			<tablename>number of contained subsystems</tablename>
			<name>application</name>
			<value>1</value>
		</metric>

		<metric>
			<tablename>number of contained subsystems</tablename>
			<name>external</name>
			<value>1</value>
		</metric>

		<metric>
			<tablename>number of contained subsystems</tablename>
			<name>persistence</name>
			<value>1</value>
		</metric>

		<metric>
			<tablename>number of contained subsystems</tablename>
			<name>model</name>
			<value>3</value>
		</metric>


		<metric>
			<tablename>number of outgoing dependencies</tablename>
			<name>application</name>
			<value>2</value>
		</metric>

		<metric>
			<tablename>number of outgoing dependencies</tablename>
			<name>model</name>
			<value>1</value>
		</metric>

		<metric>
			<tablename>number of outgoing dependencies</tablename>
			<name>persistence</name>
			<value>0</value>
		</metric>

		<metric>
			<tablename>number of outgoing dependencies to project external</tablename>
			<name>application</name>
			<value>1</value>
		</metric>

		<metric>
			<tablename>number of outgoing dependencies to project external</tablename>
			<name>model</name>
			<value>0</value>
		</metric>

	</pagemetrics>

	<pagemetrics>
		<scanfile>layer-cycle-participation.html</scanfile>
		<verifytext>layers directly participating in cycles (2)</verifytext>
	</pagemetrics>

	<!-- subsystems -->
	<pagemetrics>
		<scanfile>subsystem-metrics.html</scanfile>

		<metric>
			<tablename>number of contained packages</tablename>
			<name>application::vehicle</name>
			<value>1</value>
		</metric>

		<metric>
			<tablename>number of contained packages</tablename>
			<name>external::logging</name>
			<value>1</value>
		</metric>

		<metric>
			<tablename>number of contained packages</tablename>
			<name>model::company</name>
			<value>1</value>
		</metric>

		<metric>
			<tablename>number of contained packages</tablename>
			<name>model::other</name>
			<value>1</value>
		</metric>

		<metric>
			<tablename>number of contained packages</tablename>
			<name>persistence::vehicle</name>
			<value>1</value>
		</metric>

		<metric>
			<tablename>number of contained packages</tablename>
			<name>model::vehicle</name>
			<value>2</value>
		</metric>

		<metric>
			<tablename>number of outgoing dependencies</tablename>
			<name>application::vehicle</name>
			<value>3</value>
		</metric>

		<metric>
			<tablename>number of outgoing dependencies</tablename>
			<name>model::vehicle</name>
			<value>3</value>
		</metric>

		<metric>
			<tablename>number of outgoing dependencies</tablename>
			<name>model::company</name>
			<value>1</value>
		</metric>

		<metric>
			<tablename>number of outgoing dependencies</tablename>
			<name>model::other</name>
			<value>1</value>
		</metric>

		<metric>
			<tablename>number of outgoing dependencies</tablename>
			<name>persistence::vehicle</name>
			<value>0</value>
		</metric>

	</pagemetrics>

	<pagemetrics>
		<scanfile>subsystem-cycle-participation.html</scanfile>
		<verifytext>subsystems directly participating in cycles (4)</verifytext>
	</pagemetrics>

	<!-- check max limit of cycles to find -->
	<pagemetrics>
		<scanfile>navigation-bar.html</scanfile>
		<verifytext>cycles exist (7)</verifytext>
	</pagemetrics>

</testmetrics>

=== dheraclio/dependometer/dependometer-java/src/test/test-dependencies/combination/testconfig.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE testmetrics SYSTEM "../testconfig.dtd">

<testmetrics> <!-- see dependometer-cpp for more examples -->
	<pagemetrics>

		<scanfile>package-metrics.html</scanfile>

		<!-- check type dependencies related to annotations -->
		<metric>
			<tablename>average component dependency (ACD)</tablename>
			<name>combination.one</name>
			<value>6.0</value>
		</metric>

		<metric>
			<tablename>average component dependency (ACD)</tablename>
			<name>combination.two</name>
			<value>6.0</value>
		</metric>

	</pagemetrics>

</testmetrics>

=== dheraclio/dependometer/dependometer-java-1.2.7/src/test/test-dependencies/staticImport/testconfig.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE testmetrics SYSTEM "../testconfig.dtd">

<testmetrics> <!-- see dependometer-cpp for more examples -->
	<pagemetrics>
		<scanfile>project.html</scanfile>
		<metric>
			<name>number of project internal types</name>
			<value>4</value>
		</metric>
	</pagemetrics>
	
		<pagemetrics>

		<scanfile>type-metrics.html</scanfile>

		<!-- check type dependencies related to annotations -->
		<metric>
			<tablename>number of outgoing dependencies</tablename>
			<name>staticImport.one.Type</name>
			<value>3</value>
		</metric>

	</pagemetrics>
</testmetrics>
