=== dheraclio/dependometer/dependometer-cpp-1.2.7/src/test/test-dependencies/testconfig.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT testmetrics (pagemetrics+) >

<!ELEMENT pagemetrics (scanfile,metric*,verifytext*) >

<!ELEMENT metric (name|tablename|value)* >

<!ELEMENT name (#PCDATA) >

<!ELEMENT scanfile (#PCDATA) >

<!ELEMENT tablename (#PCDATA) >

<!ELEMENT value (#PCDATA) >

<!ELEMENT verifytext (#PCDATA) >

=== dheraclio/dependometer/dependometer-cpp/src/test/test-dependencies/assertions/testconfig.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE testmetrics SYSTEM "../testconfig.dtd">

<testmetrics>

   <pagemetrics>
   
		<scanfile>project.html</scanfile>
	
		<metric>
	 	 <name>number of assertions</name>
	 	 <value>1</value>
		</metric>
 	
 		<metric>
	 	 <name>average usage of assertions per class</name>
	 	 <value>1.0</value>
		</metric>
 	
 	</pagemetrics>
 	
 	
</testmetrics>
