=== dheraclio/dependometer/dependometer-core-1.2.7/src/test/resources/test_scenario.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="project">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="name" type="xs:string" nillable="false"/>
				<xs:element name="description" type="xs:string"/>
				<xs:element ref="type" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="type">
		<xs:complexType>
			<xs:sequence>
			<xs:element name="name" type="xs:string" nillable="false"/>
				<xs:element name="superinterface" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="superclass" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="property" maxOccurs="unbounded"/>
				<xs:element name="depends-on" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<!--TODO: a property occurs only once in a type-->
	<xs:element name="property">
		<xs:simpleType>

					<xs:restriction base="xs:string">
						<xs:enumeration value="public"/>
						<xs:enumeration value="protected"/>
						<xs:enumeration value="private"/>
						<xs:enumeration value="abstract"/>
						<xs:enumeration value="interface"/>
						<xs:enumeration value="final"/>
						<xs:enumeration value="class"/>
						<xs:enumeration value="enum"/>
					</xs:restriction>

		</xs:simpleType>
	</xs:element>
	
</xs:schema>

=== dheraclio/dependometer/dependometer-core/src/test/resources/metrics/interfaces.xml
<?xml version="1.0" encoding="UTF-8"?>
<project name="String" xsi:noNamespaceSchemaLocation="../test_scenario.xsd"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<name>TestProject Interfaces</name>
	<description>Contains interaces</description>
	<type>
		<name>sample.ClassWithInterfaces</name>
		<property>public</property>
		<property>class</property>
	</type>
	<type>
		<name>sample.SimpleInterfaceA</name>
		<property>public</property>
		<property>interface</property>
	</type>
	<type>
		<name>sample.SimpleInterfaceB</name>
		<property>public</property>
		<property>interface</property>
	</type>
	<type>
		<name>sample.AbstractClassWithInterface</name>
		<property>abstract</property>
		<property>class</property>
	</type>
</project>

=== dheraclio/dependometer/dependometer-core-1.2.7/src/test/resources/metrics/package_hierarchy.xml
<?xml version="1.0" encoding="UTF-8"?>
<project name="String" xsi:noNamespaceSchemaLocation="../test_scenario.xsd"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<name>TestProject Package Hierarchy</name>
	<description>Contains package hierarchy</description>
	<type>
		<name>sample1.SimpleClass1</name>
		<property>public</property>
		<property>class</property>
	</type>
	<type>
		<name>sample2.SimpleClass2</name>
		<property>public</property>
		<property>class</property>
	</type>
	<type>
		<name>sample2.sub1.SimpleClass3</name>
		<property>public</property>
		<property>class</property>
	</type>
		<type>
		<name>sample2.sub2.subsub1.SimpleClass4</name>
		<property>public</property>
		<property>class</property>
	</type>
	
</project>

=== dheraclio/dependometer/dependometer-core/src/test/resources/metrics/ccdAcd2DirectlyAndIndirectlyDependentOnComponent.xml
<?xml version="1.0" encoding="UTF-8"?>
<project name="String" xsi:noNamespaceSchemaLocation="../test_scenario.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<name>TestProject One Class</name>
	<description>Contains four connected classes without cycle (directed depdency graph) and one unconnected class, CCD=11</description>
	<type>
		<name>sample1.ClassA</name>
		<property>public</property>
		<property>class</property>
		<depends-on>sample2.ClassB</depends-on>
	</type>
	<type>
		<name>sample2.ClassB</name>
		<property>public</property>
		<property>class</property>
	</type>
	<type>
		<name>sample3.ClassC</name>
		<property>public</property>
		<property>class</property>
		<depends-on>sample1.ClassA</depends-on>
	</type>
	<type>
		<name>sample3.ClassD</name>
		<property>public</property>
		<property>class</property>
		<depends-on>sample3.ClassC</depends-on>
		<depends-on>sample1.ClassA</depends-on>
	</type>
	<type>
		<name>sample3.ClassE</name>
		<property>public</property>
		<property>class</property>
	</type>
</project>

=== dheraclio/dependometer/dependometer-core/src/test/resources/metrics/ccdAcd4DependencyCycleAtLowerLevel.xml
<?xml version="1.0" encoding="UTF-8"?>
<project name="String" xsi:noNamespaceSchemaLocation="../test_scenario.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<name>TestProject One Class</name>
	<description>Contains six classes, some of them are in a cycle, some not, CCD=27</description>
	<type>
		<name>sample2.ClassA</name>
		<property>public</property>
		<property>class</property>
		<depends-on>sample2.ClassB</depends-on>
		<depends-on>sample1.ClassC</depends-on>
	</type>
	<type>
		<name>sample2.ClassB</name>
		<property>public</property>
		<property>class</property>
		<depends-on>sample1.ClassD</depends-on>
	</type>
	<type>
		<name>sample1.ClassC</name>
		<property>public</property>
		<property>class</property>
		<depends-on>sample1.ClassD</depends-on>
		<depends-on>sample1.ClassE</depends-on>
	</type>
		<type>
		<name>sample1.ClassD</name>
		<property>public</property>
		<property>class</property>
		<depends-on>sample1.ClassE</depends-on>
		<depends-on>sample1.ClassF</depends-on>
	</type>
	<type>
		<name>sample1.ClassE</name>
		<property>public</property>
		<property>class</property>
		<depends-on>sample1.ClassF</depends-on>
	</type>
	<type>
		<name>sample1.ClassF</name>
		<property>public</property>
		<property>class</property>
		<depends-on>sample1.ClassC</depends-on>
	</type>
</project>

=== dheraclio/dependometer/dependometer-core/src/test/resources/metrics/abstract_types.xml
<?xml version="1.0" encoding="UTF-8"?>
<project name="String" xsi:noNamespaceSchemaLocation="../test_scenario.xsd"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<name>TestProject Abstract Types</name>
	<description>Contains abstract types</description>
	<type>
		<name>sample.SimpleClass</name>
		<property>public</property>
		<property>class</property>
	</type>
	<type>
		<name>sample.SimpleInterfaceA</name>
		<property>public</property>
		<property>interface</property>
	</type>
	<type>
		<name>sample.AbstractClass</name>
		<property>abstract</property>
		<property>class</property>
	</type>
	<type>
		<name>sample.AbstractClassWithInterface</name>
		<property>abstract</property>
		<property>class</property>
		<depends-on>sample.SimpleInterfaceA</depends-on>
	</type>
</project>

=== dheraclio/dependometer/dependometer-core-1.2.7/src/test/resources/metrics/subsystems_and_layers.xml
<?xml version="1.0" encoding="UTF-8"?>
<project name="String" xsi:noNamespaceSchemaLocation="../test_scenario.xsd"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<name>TestProject Subsystems and Layers</name>
	<description>Contains multiple packages and subpackges usable in an architecture definition</description>
	<type>
		<name>one.ClassA</name>
		<property>public</property>
		<property>class</property>
	</type>
	<type>
		<name>one.sub1.ClassB</name>
		<property>public</property>
		<property>class</property>
	</type>
	<type>
		<name>one.sub2.ClassC</name>
		<property>public</property>
		<property>class</property>
	</type>
	<type>
		<name>two.ClassD</name>
		<property>public</property>
		<property>class</property>
	</type>
	<type>
		<name>two.sub1.ClassE</name>
		<property>public</property>
		<property>class</property>
	</type>
	<type>
		<name>two.sub2.ClassF</name>
		<property>public</property>
		<property>class</property>
	</type>
		<type>
		<name>two.sub2.subsub1.ClassG</name>
		<property>public</property>
		<property>class</property>
	</type>
	<type>
		<name>external.sub1.ClassXYZ</name>
		<property>public</property>
		<property>class</property>
	</type>
</project>

=== dheraclio/dependometer/dependometer-core/src/test/resources/metrics/ccdAcd3DependencyCycle3SequentiallyDependentComponents.xml
<?xml version="1.0" encoding="UTF-8"?>
<project name="String" xsi:noNamespaceSchemaLocation="../test_scenario.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<name>TestProject One Class</name>
	<description>Contains 3 classes which are all in a cycle, CCD=n^2=9</description>
	<type>
		<name>sample1.ClassA</name>
		<property>public</property>
		<property>class</property>
		<depends-on>sample2.ClassB</depends-on>
	</type>
	<type>
		<name>sample2.ClassB</name>
		<property>public</property>
		<property>class</property>
		<depends-on>sample1.ClassC</depends-on>
	</type>
	<type>
		<name>sample1.ClassC</name>
		<property>public</property>
		<property>class</property>
		<depends-on>sample1.ClassA</depends-on>
	</type>
</project>

=== dheraclio/dependometer/dependometer-core/src/test/resources/metrics/ccdAcd5BinaryTree.xml
<?xml version="1.0" encoding="UTF-8"?>
<project name="String" xsi:noNamespaceSchemaLocation="../test_scenario.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<name>TestProject One Class</name>
	<description>Contains 7 classes in a balanced binary tree, CCD= (n+1)log(n+1)-n = 17</description>
	<type>
		<name>sample1.ClassA</name>
		<property>public</property>
		<property>class</property>
		<depends-on>sample2.ClassB</depends-on>
		<depends-on>sample2.ClassC</depends-on>
	</type>
	<type>
		<name>sample2.ClassB</name>
		<property>public</property>
		<property>class</property>
		<depends-on>sample3.ClassD</depends-on>
		<depends-on>sample3.ClassE</depends-on>
	</type>
	<type>
		<name>sample2.ClassC</name>
		<property>public</property>
		<property>class</property>
		<depends-on>sample3.ClassF</depends-on>
		<depends-on>sample3.ClassG</depends-on>
	</type>
		<type>
		<name>sample3.ClassD</name>
		<property>public</property>
		<property>class</property>
	</type>
	<type>
		<name>sample3.ClassE</name>
		<property>public</property>
		<property>class</property>
	</type>
	<type>
		<name>sample3.ClassF</name>
		<property>public</property>
		<property>class</property>
	</type>
		<type>
		<name>sample3.ClassG</name>
		<property>public</property>
		<property>class</property>
	</type>
</project>
