=== dheraclio/dependometer/dependometer-core-1.2.7/src/test/resources/test_scenario.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="project">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="name" type="xs:string" nillable="false"/>
				<xs:element name="description" type="xs:string"/>
				<xs:element ref="type" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="type">
		<xs:complexType>
			<xs:sequence>
			<xs:element name="name" type="xs:string" nillable="false"/>
				<xs:element name="superinterface" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="superclass" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="property" maxOccurs="unbounded"/>
				<xs:element name="depends-on" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<!--TODO: a property occurs only once in a type-->
	<xs:element name="property">
		<xs:simpleType>

					<xs:restriction base="xs:string">
						<xs:enumeration value="public"/>
						<xs:enumeration value="protected"/>
						<xs:enumeration value="private"/>
						<xs:enumeration value="abstract"/>
						<xs:enumeration value="interface"/>
						<xs:enumeration value="final"/>
						<xs:enumeration value="class"/>
						<xs:enumeration value="enum"/>
					</xs:restriction>

		</xs:simpleType>
	</xs:element>
	
</xs:schema>

=== dheraclio/dependometer/dependometer-core/src/test/resources/metrics/ccdAcd1IndependentComponents.xml
<?xml version="1.0" encoding="UTF-8"?>
<project name="String" xsi:noNamespaceSchemaLocation="../test_scenario.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<name>TestProject One Class</name>
	<description>Contains two non connected simple classes, CCD=n=2</description>
	<type>
		<name>sample1.ClassA</name>
		<property>public</property>
		<property>class</property>
	</type>
	<type>
		<name>sample2.ClassB</name>
		<property>public</property>
		<property>class</property>
	</type>
</project>

=== dheraclio/dependometer/dependometer-core-1.2.7/src/test/resources/metrics/simple_cycle.xml
<?xml version="1.0" encoding="UTF-8"?>
	<!-- simple cycle exist between ClassB and ClassC-->
<project name="String" xsi:noNamespaceSchemaLocation="../test_scenario.xsd"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<name>TestProject Simple Cycle</name>
	<description>Contains one simple cylce with two classes</description>
	<type>
		<name>sample.ClassA</name>
		<property>class</property>
		<depends-on>sample.ClassB</depends-on>
	</type>
	<type>
		<name>sample.ClassB</name>
		<property>class</property>
		<depends-on>sample.ClassC</depends-on>
	</type>
	<type>
		<name>sample.ClassC</name>
		<property>class</property>
		<depends-on>sample.ClassA</depends-on>
	</type>
</project>

=== dheraclio/dependometer/dependometer-core-1.2.7/src/test/resources/metrics/simple_package.xml
<?xml version="1.0" encoding="UTF-8"?>
	<!-- simple cycle exist between ClassB and ClassC-->
<project name="String" xsi:noNamespaceSchemaLocation="../test_scenario.xsd"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<name>TestProject Simple Cycle</name>
	<description>Contains classes in different packages.</description>
	<type>
		<name>sample1.subpack1.ClassA</name>
		<property>public</property>
		<property>class</property>
	</type>
	<type>
		<name>sample1.subpack2.ClassB</name>
		<property>public</property>
		<property>class</property>
	</type>
	<type>
		<name>sample1.subpack2.ClassC</name>
		<property>public</property>
		<property>class</property>
	</type>
	<type>
		<name>sample2.ClassD</name>
		<property>public</property>
		<property>class</property>
	</type>
</project>

=== dheraclio/dependometer/dependometer-core-1.2.7/src/test/resources/sample.xml
<?xml version="1.0" encoding="UTF-8"?>
<project name="String" xsi:noNamespaceSchemaLocation="test_scenario.xsd"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<name>TestProject</name>
	<description>This is a test.</description>
	<type>
		<name>com.valtech.source.project.domain.IEntity</name>
		<property>public</property>
		<property>interface</property>
	</type>
	<type>
		<name>com.valtech.source.project.domain.AbstractEntity</name>
		<property>public</property>
		<property>class</property>
		<property>abstract</property>
	</type>
	<type>
		<name>com.valtech.source.project.domain.Employee</name>
		<superclass>com.valtech.source.project.domain.AbstractEntity</superclass>
		<property>public</property>
		<property>class</property>
		<depends-on>com.valtech.source.project.domain.Adresse
		</depends-on>
	</type>
	<type>
		<name>com.valtech.source.project.domain.Adresse</name>
		<property>public</property>
		<property>class</property>
	</type>
	<type>
		<name>com.valtech.source.project.business.IService</name>
		<property>public</property>
		<property>interface</property>
		<depends-on>com.valtech.source.project.domain.Employee
		</depends-on>
	</type>

	<type>
		<name>com.valtech.source.project.business.Service</name>
		<property>public</property>
		<property>class</property>
		<depends-on>com.valtech.source.project.domain.Employee
		</depends-on>
	</type>
</project>

=== dheraclio/dependometer/dependometer-core-1.2.7/src/test/resources/metrics/package_cycles.xml
<?xml version="1.0" encoding="UTF-8"?>
	<!-- simple cycle exist between ClassB and ClassC-->
<project name="String" xsi:noNamespaceSchemaLocation="../test_scenario.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<name>TestProject Multiple Package Cycles</name>
	<description>Contains multiple package cycles</description>
	<type>
		<name>sample1.ClassA</name>
		<property>class</property>
	</type>
	<type>
		<name>sample1.ClassB</name>
		<property>class</property>
		<depends-on>sample2.ClassE</depends-on>
	</type>
	<type>
		<name>sample1.ClassC</name>
		<property>class</property>
		<depends-on>sample2.ClassD</depends-on>
	</type>
	<type>
		<name>sample2.ClassD</name>
		<property>class</property>
		<depends-on>sample3.ClassH</depends-on>
	</type>
	<type>
		<name>sample2.ClassE</name>
		<property>class</property>
		<depends-on>sample3.ClassG</depends-on>
	</type>
	<type>
		<name>sample2.ClassF</name>
		<property>class</property>
		<depends-on>sample3.ClassI</depends-on>
	</type>
	<type>
		<name>sample3.ClassG</name>
		<property>class</property>
		<depends-on>sample1.ClassA</depends-on>
		<depends-on>sample2.ClassF</depends-on>
	</type>
	<type>
		<name>sample3.ClassH</name>
		<property>class</property>
		<depends-on>sample1.ClassC</depends-on>
	</type>
	<type>
		<name>sample3.ClassI</name>
		<property>class</property>
	</type>

</project>
