=== dheraclio/dependometer/dependometer-core-1.2.7/src/test/resources/test_scenario.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="project">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="name" type="xs:string" nillable="false"/>
				<xs:element name="description" type="xs:string"/>
				<xs:element ref="type" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="type">
		<xs:complexType>
			<xs:sequence>
			<xs:element name="name" type="xs:string" nillable="false"/>
				<xs:element name="superinterface" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="superclass" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="property" maxOccurs="unbounded"/>
				<xs:element name="depends-on" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<!--TODO: a property occurs only once in a type-->
	<xs:element name="property">
		<xs:simpleType>

					<xs:restriction base="xs:string">
						<xs:enumeration value="public"/>
						<xs:enumeration value="protected"/>
						<xs:enumeration value="private"/>
						<xs:enumeration value="abstract"/>
						<xs:enumeration value="interface"/>
						<xs:enumeration value="final"/>
						<xs:enumeration value="class"/>
						<xs:enumeration value="enum"/>
					</xs:restriction>

		</xs:simpleType>
	</xs:element>
	
</xs:schema>

=== dheraclio/dependometer/dependometer-core-1.2.7/src/test/resources/metrics/architecture_dependencies.xml
<?xml version="1.0" encoding="UTF-8"?>
<project name="String" xsi:noNamespaceSchemaLocation="../test_scenario.xsd"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<name>TestProject Architecture Dependencies</name>
	<description>Contains multiple architecure definition with dependencies, no cycles</description>

	<!-- application layer -->
	<type>
		<name>application.core.ClassA</name>
		<property>public</property>
		<property>class</property>
		<depends-on>application.core.config.ClassC1</depends-on>
		<depends-on>services.ClassD</depends-on>
		<depends-on>services.shop.ClassE</depends-on>
		<depends-on>services.catalogue.export.ClassG</depends-on>
		<depends-on>external.sub1.ClassXYZ</depends-on>
	</type>
	<type>
		<name>application.core.startup.ClassB</name>
		<property>public</property>
		<property>class</property>
		<depends-on>services.shop.ClassE</depends-on>
	</type>
	<type>
		<name>application.core.config.ClassC1</name>
		<property>public</property>
		<property>class</property>
		<depends-on>services.catalogue.export.ClassG</depends-on>
	</type>
	<type>
		<name>application.core.config.ClassC2</name>
		<property>public</property>
		<property>class</property>
		<depends-on>services.catalogue.export.ClassG</depends-on>
	</type>
	<type>
		<name>application.core.config.ClassC2$Nested1</name>
		<property>public</property>
		<property>class</property>
		<depends-on>services.catalogue.export.ClassG</depends-on>
	</type>
	<type>
		<name>application.core.config.ClassC2$Nested2</name>
		<property>public</property>
		<property>class</property>
		<depends-on>services.catalogue.export.ClassG</depends-on>
	</type>

	<!-- service layer -->
	<type>
		<name>services.ClassD</name>
		<property>public</property>
		<property>class</property>
		<depends-on>services.catalogue.ClassF</depends-on>
	</type>
	<type>
		<name>services.shop.ClassE</name>
		<property>public</property>
		<property>class</property>
		<depends-on>services.catalogue.ClassF</depends-on>
	</type>
	<type>
		<name>services.catalogue.ClassF</name>
		<property>public</property>
		<property>class</property>
	</type>
	<type>
		<name>services.catalogue.export.ClassG</name>
		<property>public</property>
		<property>class</property>
		<depends-on>external.sub1.ClassXYZ</depends-on>
	</type>

	<!-- project external -->
	<type>
		<name>external.sub1.ClassXYZ</name>
		<property>public</property>
		<property>class</property>
	</type>
</project>

=== dheraclio/dependometer/dependometer-core/src/test/resources/metrics/package_external_internal_dependencies.xml
<?xml version="1.0" encoding="UTF-8"?>
<project name="String" xsi:noNamespaceSchemaLocation="../test_scenario.xsd"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<name>TestProject Package internal/external dependencies</name>
	<description>Contains package internal and package external dependencies</description>
	<type>
		<name>sample1.SimpleClass1</name>
		<property>public</property>
		<property>class</property>
		<depends-on>sample2.AnotherClass1</depends-on>
		<depends-on>sample1.SimpleClass3</depends-on>
	</type>
	<type>
		<name>sample1.SimpleClass2</name>
		<property>public</property>
		<property>class</property>
		<depends-on>sample1.SimpleClass3</depends-on>
	</type>
	<type>
		<name>sample1.SimpleClass3</name>
		<property>public</property>
		<property>class</property>
		<depends-on>sample1.SimpleClass1</depends-on>
	</type>
	<type>
		<name>sample1.SimpleClass4</name>
		<property>protected</property>
		<property>class</property>
		<depends-on>sample1.SimpleClass1</depends-on>
		<depends-on>sample2.AnotherClass1</depends-on>
	</type>
	<type>
		<name>sample2.AnotherClass1</name>
		<property>public</property>
		<property>class</property>
		<depends-on>sample1.SimpleClass1</depends-on>
	</type>
	<type>
		<name>sample2.AnotherClass2</name>
		<property>public</property>
		<property>class</property>
		<depends-on>sample1.SimpleClass1</depends-on>
	</type>
	<type>
		<name>sample2.AnotherClass2$Nested1</name>
		<property>public</property>
		<property>class</property>
		<depends-on>sample1.SimpleClass1</depends-on>
	</type>
</project>

=== dheraclio/dependometer/dependometer-core-1.2.7/src/test/resources/metrics/cycle_groups.xml
<?xml version="1.0" encoding="UTF-8"?>
	<!-- simple cycle exist between ClassB and ClassC-->
<project name="String" xsi:noNamespaceSchemaLocation="../test_scenario.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<name>TestProject Multiple Cycles</name>
	<description>Contains multiple compilation unit cycles</description>
	<type>
		<name>sample.ClassA</name>
		<property>class</property>
		<depends-on>sample.ClassD</depends-on>
		<depends-on>sample.ClassB</depends-on>
	</type>
	<type>
		<name>sample.ClassB</name>
		<property>class</property>
		<depends-on>sample.ClassC</depends-on>
		<depends-on>sample.ClassD</depends-on>
	</type>
	<type>
		<name>sample.ClassC</name>
		<property>class</property>
		<depends-on>sample.ClassA</depends-on>
		<depends-on>sample.ClassF</depends-on>
	</type>
	<type>
		<name>sample.ClassD</name>
		<property>class</property>
		<depends-on>sample.ClassC</depends-on>
	</type>
	<type>
		<name>sample.ClassE</name>
		<property>class</property>
		<depends-on>sample.ClassF</depends-on>
	</type>
	<type>
		<name>sample.ClassF</name>
		<property>class</property>
		<depends-on>sample.ClassE</depends-on>
	</type>

</project>

=== dheraclio/dependometer/dependometer-core-1.2.7/src/test/resources/metrics/class_hierarchy.xml
<?xml version="1.0" encoding="UTF-8"?>
<project name="String" xsi:noNamespaceSchemaLocation="../test_scenario.xsd"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<name>TestProject Class Hierarchy</name>
	<description>Contains a class hierarchy</description>
	<type>
		<name>sample.SubClass1</name>
		<superclass>sample.SuperClassA</superclass>
		<superclass>sample.SuperClassB</superclass>
		<property>public</property>
		<property>class</property>
	</type>
	<type>
	<name>sample.SubClass2</name>
		<superclass>sample.SuperClassD</superclass>
		<property>public</property>
		<property>class</property>
	</type>
	<type>
		<name>sample.SuperClassA</name>
		<superclass>sample.SuperClassC</superclass>
		<property>public</property>
		<property>class</property>
	</type>
	<type>
		<name>sample.SuperClassB</name>
		<property>public</property>
		<property>class</property>
		<property>abstract</property>
	</type>
	<type>
		<name>sample.SuperClassC</name>
		<superclass>sample.SuperClassD</superclass>
		<property>public</property>
		<property>class</property>
		<property>abstract</property>
	</type>
	<type>
		<name>sample.SuperClassD</name>
		<superinterface>sample.InterfaceA</superinterface>
		<property>public</property>
		<property>class</property>
		<property>abstract</property>
	</type>
	<type>
		<name>sample.InterfaceA</name>
		<property>public</property>
		<property>interface</property>
	</type>
</project>

=== dheraclio/dependometer/dependometer-core/src/test/resources/metrics/caCe_PackageDep_Out_InOut_In_Independent.xml
<?xml version="1.0" encoding="UTF-8"?>
<project name="String" xsi:noNamespaceSchemaLocation="../test_scenario.xsd"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<name>Ca Ce - afferent efferent coupling</name>
	<description></description>
	<!-- independent package -->
	<type>
		<name>p0.C01</name>
		<property>public</property>
		<property>class</property>
	</type>
	<!--  dependencies to p2, package internal dependencies	-->
	<type>
		<name>p1.C11</name>
		<property>public</property>
		<property>class</property>
		<depends-on>p2.C21</depends-on>
		<depends-on>p2.C22</depends-on>
	</type>
	<type>
		<name>p1.C12</name>
		<property>public</property>
		<property>class</property>
		<depends-on>p1.C11</depends-on>
	</type>
	<!--  dependencies from p1 and dependencies to p3 -->
	<type>
		<name>p2.C21</name>
		<property>public</property>
		<property>class</property>
		<depends-on>p3.C31</depends-on>
	</type>
	<type>
		<name>p2.C22</name>
		<property>public</property>
		<property>class</property>
		<depends-on>p3.C31</depends-on>
	</type>
	<type>
		<name>p2.C23</name>
		<property>public</property>
		<property>class</property>
		<depends-on>p3.C33</depends-on>
	</type>
	<!-- dependencies from p2 -->
	<type>
		<name>p3.C31</name>
		<property>public</property>
		<property>class</property>
	</type>
	<type>
		<name>p3.C32</name>
		<property>public</property>
		<property>class</property>
	</type>
	<type>
		<name>p3.C33</name>
		<property>public</property>
		<property>class</property>
		<depends-on>p3.C31</depends-on>
	</type>

</project>

=== dheraclio/dependometer/dependometer-core/src/test/resources/metrics/multiple_types_in_one_cu.xml
<?xml version="1.0" encoding="UTF-8"?>
<project name="String" xsi:noNamespaceSchemaLocation="../test_scenario.xsd"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<name>TestProject Abstract Types</name>
	<description>Contains multiple types in one comilation unit</description>
	<type>
		<name>sample.ClassWithNestedTypes</name>
		<property>public</property>
		<property>class</property>
	</type>
	<type>
		<name>sample.ClassWithNestedTypes$Nested1</name>
		<property>public</property>
		<property>class</property>
	</type>
	<type>
		<name>sample.ClassWithNestedTypes$Nested2</name>
		<property>public</property>
		<property>class</property>
		<property>abstract</property>
	</type>
	<type>
		<name>sample.ClassWithNestedTypes$INested1</name>
		<property>public</property>
		<property>interface</property>
	</type>
	<type>
	<name>sample.ClassWithNestedTypes$Nested1$NestedNested1</name>
		<property>public</property>
		<property>class</property>
	</type>
	<type>
		<name>sample.InterfaceWithNestedTypes</name>
		<property>public</property>
		<property>interface</property>
	</type>
	<type>
		<name>sample.InterfaceWithNestedTypes$Nested1</name>
		<property>public</property>
		<property>class</property>
	</type>
	<type>
		<name>sample.InterfaceWithNestedTypes$INested1</name>
		<property>public</property>
		<property>interface</property>
	</type>
	<type>
		<name>sample.InterfaceWithNestedTypes$Nested2</name>
		<property>public</property>
		<property>class</property>
		<property>abstract</property>
	</type>
</project>

=== dheraclio/dependometer/dependometer-core/src/test/resources/metrics/type_access.xml
<?xml version="1.0" encoding="UTF-8"?>
<project name="String" xsi:noNamespaceSchemaLocation="../test_scenario.xsd"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<name>TestProject Type access</name>
	<description>Contains types with different visibility</description>
	<type>
		<name>sample.PublicClass</name>
		<property>public</property>
		<property>class</property>
	</type>
	<type>
		<name>sample.ProtectedClass</name>
		<property>protected</property>
		<property>class</property>
	</type>
	<type>
		<name>sample.PrivateClass</name>
		<property>private</property>
		<property>class</property>
	</type>
	<type>
		<name>sample.PublicFinalClass</name>
		<property>public</property>
		<property>final</property>
		<property>class</property>
	</type>
</project>

=== dheraclio/dependometer/dependometer-core-1.2.7/src/test/resources/metrics/interface_hierarchy.xml
<?xml version="1.0" encoding="UTF-8"?>
<project name="String" xsi:noNamespaceSchemaLocation="../test_scenario.xsd"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<name>TestProject Interface Hierarchy</name>
	<description>Contains a interace hierarchy</description>
	<type>
		<name>sample.SubInterface1</name>
		<superinterface>sample.SuperInterfaceA</superinterface>
		<superinterface>sample.SuperInterfaceB</superinterface>
		<property>public</property>
		<property>interface</property>
	</type>
	<type>
		<name>sample.SubInterface2</name>
		<superinterface>sample.SuperInterfaceD</superinterface>
		<property>public</property>
		<property>interface</property>
	</type>
	<type>
		<name>sample.SuperInterfaceA</name>
		<property>public</property>
		<property>interface</property>
	</type>
	<type>
		<name>sample.SuperInterfaceB</name>
		<superinterface>sample.SuperInterfaceC</superinterface>
		<property>public</property>
		<property>interface</property>
	</type>
	<type>
		<name>sample.SuperInterfaceC</name>
		<superinterface>sample.SuperInterfaceD</superinterface>
		<property>public</property>
		<property>interface</property>
	</type>
	<type>
		<name>sample.SuperInterfaceD</name>
		<property>public</property>
		<property>interface</property>
	</type>
	<type>
		<name>sample.ClassWithInterface</name>
		<property>public</property>
		<property>class</property>
	</type>
</project>
