=== dheraclio/dependometer/dependometer-core-1.2.7/src/main/resources/com/valtech/source/dependometer/app/configprovider/filebased/xml/Configuration.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT input EMPTY>
<!ATTLIST input dir CDATA #REQUIRED>

<!ELEMENT system-include-path EMPTY>
<!ATTLIST system-include-path dir CDATA #REQUIRED>

<!ELEMENT system-define EMPTY>
<!ATTLIST system-define
	symbol CDATA #REQUIRED
	macro CDATA #REQUIRED
>

<!ELEMENT depends-upon EMPTY>
<!ATTLIST depends-upon name NMTOKEN #REQUIRED>

<!ELEMENT ignore EMPTY>
<!ATTLIST ignore
	fromType CDATA #REQUIRED
	toType CDATA #REQUIRED
>

<!ELEMENT include-package EMPTY>
<!ATTLIST include-package name CDATA #REQUIRED>

<!ELEMENT exclude-package EMPTY>
<!ATTLIST exclude-package name CDATA #REQUIRED>

<!ELEMENT exclude-compilation-unit EMPTY>
<!ATTLIST exclude-compilation-unit name CDATA #REQUIRED>

<!ELEMENT exclude-subsystem EMPTY>
<!ATTLIST exclude-subsystem name CDATA #REQUIRED>
<!ELEMENT vertical-slices (exclude-subsystem*)>
<!ATTLIST vertical-slices checkDependencies NMTOKEN #IMPLIED>
<!ATTLIST vertical-slices cumulateDependencies NMTOKEN #IMPLIED>
<!ATTLIST vertical-slices maxCycles NMTOKEN #IMPLIED>

<!ELEMENT assertion EMPTY>
<!ATTLIST assertion pattern CDATA #REQUIRED>

<!ELEMENT lower-threshold EMPTY>
<!ATTLIST lower-threshold name NMTOKEN #REQUIRED>
<!ATTLIST lower-threshold value NMTOKEN #REQUIRED>

<!ELEMENT upper-threshold EMPTY>
<!ATTLIST upper-threshold name NMTOKEN #REQUIRED>
<!ATTLIST upper-threshold value NMTOKEN #REQUIRED>

<!ELEMENT layer (description?,subsystem+,depends-upon*)>
<!ATTLIST layer name NMTOKEN #REQUIRED>

<!ELEMENT listener EMPTY>
<!ATTLIST listener
	class NMTOKEN #REQUIRED
	args CDATA #REQUIRED
>

<!ELEMENT project (input+,system-include-path*, system-define*,include-package+,exclude-package*,exclude-compilation-unit*,vertical-slices?,listener+,assertion?,ignore*,skip*,refactor*,lower-threshold*,upper-threshold*,layer*)>
<!ATTLIST project
	name CDATA #REQUIRED
    numberOfCycleAnalysisProgressFeedbackOnConsole NMTOKEN #IMPLIED
	numberOfCyclesFeedbackOnConsole NMTOKEN #IMPLIED
	checkLayerDependencies NMTOKEN #IMPLIED
	checkSubsystemDependencies NMTOKEN #IMPLIED
	checkPackageDependencies NMTOKEN #IMPLIED
	cumulateLayerDependencies NMTOKEN #IMPLIED
	cumulateSubsystemDependencies NMTOKEN #IMPLIED
	cumulatePackageDependencies NMTOKEN #IMPLIED
	cumulateCompilationUnitDependencies NMTOKEN #IMPLIED
	cumulateTypeDependencies NMTOKEN #IMPLIED
	ignorePhysicalStructure NMTOKEN #IMPLIED
	maxCompilationUnitCycles NMTOKEN #IMPLIED
	maxLayerCycles NMTOKEN #IMPLIED
	maxSubsystemCycles NMTOKEN #IMPLIED
	maxPackageCycles NMTOKEN #IMPLIED
	maxTypeCycles NMTOKEN #IMPLIED
	fileEncoding NMTOKEN #IMPLIED
	timeoutMinutes NMTOKEN #IMPLIED
>

<!ELEMENT refactor EMPTY>
<!ATTLIST refactor
	compilationUnit CDATA #REQUIRED
	toPackage NMTOKEN #REQUIRED
>

<!ELEMENT skip EMPTY>
<!ATTLIST skip prefix CDATA #REQUIRED>

<!ELEMENT subsystem (description?,include-package+,exclude-package*,depends-upon*)>
<!ATTLIST subsystem name NMTOKEN #REQUIRED>

<!ELEMENT description (#PCDATA)>

=== dheraclio/dependometer/dependometer-java-1.2.7/src/test/test-dependencies/metaAnnotations/dep.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE project SYSTEM "Configuration.dtd"> 

<!-- Test to verify the correct identification of dependencies if meta annotations are present in the code.
The involved package is metaAnnotations.

Expected Results:

1 dependency from MotorVehicle to Motorbike via annotation InheritanceTest.
1 dependency from MotorVehicle to annotation IntheritanceTest.
1 dependency from MotorVehicle to Engine.

1 dependency from Car to Motorbike via annotation InheritanceTest because the annotation InheritanceTest is inherited from the class MotorVehicle.
Since the annotation InheritanceTest has the argument Motorbike.class, there is no dependency created for Motorbike by this annotation.
1 dependency from Car to MotorVehicle because of inheritance.

1 dependency from Motorbike to MotorVehicle because of inheritance.
1 dependency from Motorbike to annotation DrivingPleasure.

1 dependency from Trike to Car via annotation InheritanceTest. The annotation declaration in Trike overrides the declaration in its superclass MotorVehicle.
1 dependency from Trike to annotation InheritanceTest.
1 dependency from Trike to MotorVehicle because of inheritance.


(Perhaps: 1 dependency respectively from Car, Motorbike to annotation InheritanceTest.
1 dependency respectively from Car, Trike, Motorbike to Engine.)


There are also some additional tests in this package: 
The class Car uses the annotations Override and Deprecated of the java.lang-package.
This should not create dependencies from Car to Override or Deprecated of the metaAnnotations-package.

The annotation type Fast uses the meta annotations Documented and Target. 
This should not create dependencies from Fast to Documented or Target of the metaAnnotations-package.

The classes Motorbike and Trike use the annotation Joy with the argument Car.class. Since the retention policy of the annotation type Joy is set to source, 
all usages of Joy are only visible in the sourcecode. To ensure a constant behaviour of the Dependometer regarding the input (source and class 
files or simply class files) all dependencies that are not reflected in the bytecode should be ignored. So there shouldn't be dependencies from
Motorbike and Trike respectively to Joy.

-->

<!-- 
	name 
		the project name appears in the reports
	numberOfCyclesFeedbackOnConsole (default = "1")
		Every time the configured number of cycles is reached you get an extra warning in your shell
	numberOfCycleAnalysisProgressFeedbackOnConsole (default = "1")
		Every time the remaining number of nodes was accordingly reduced you get an extra info in your shell
	checkLayerDependencies (default = "true")
	checkSubsystemDependencies (default = "true")
		"true"	all dependencies are checked against the allowed dependencies (depends-upon node)
		"false" no dependency check
	checkPackageDependencies (default = "true")
		"true" 	all package dependencies are checked against the allowed dependencies (only packages are checked that have a package description)
		"false" no dependency check
	cumulateLayerDependencies (default = "true")
	cumulateSubsystemDependencies (default = "true")
	cumulatePackageDependencies (default = "true")
	cumulateCompilationUnitDependencies (default = "true")
	cumulateTypeDependencies (default = "true")
		"true"	cumulate dependencies
		"false" no cumulation
	maxLayerCycles (default = "0")            		
	maxSubsystemCycles (default = "0")      		
	maxPackageCycles (default = "0")          		
	maxCompilationUnitCycles (default = "0")  		
	maxTypeCycles (default = "0")             		
		Configure the cycle analysis behavior to avoid an endlessly running process. As an alternativ you can start the
		dependometer with the command 'java -jar dependomter.jar -file <your configuration>' and terminate the analyis when
		ever you want with 'ctrl-c' in the shell. This is possible past the point where in the shell the message 'Terminate
		running analysis with 'ctrl-c'!' appears. Past this point you have also a valid html output. Only the cycle analyis
		output gets updated. With a corresponding refresh in your browser you can see the updated information.   
		"-2" 	no analysis
		"-1" 	cycle existence check
		"0"	like "-1" plus detailed cycle participation (which elements participate in cycles?) and levelization
		">0"	like 0" but with the provided upper limit for detected cycles (stops if 'n' cycles are reached)
-->
<project 
	name											= "Test: Combination of all tests without architecture definition" 
	numberOfCyclesFeedbackOnConsole 				= "1"
	numberOfCycleAnalysisProgressFeedbackOnConsole 	= "1"
	checkLayerDependencies							= "false"
	checkSubsystemDependencies 						= "false"
	checkPackageDependencies 						= "false"
	cumulateLayerDependencies 						= "false"
	cumulateSubsystemDependencies 					= "false"
	cumulatePackageDependencies 					= "true"
	cumulateCompilationUnitDependencies 			= "true"
	cumulateTypeDependencies 						= "true"
	maxLayerCycles             						= "0"
	maxSubsystemCycles         						= "0"
	maxPackageCycles           						= "0"
	maxCompilationUnitCycles   						= "0"
	maxTypeCycles              						= "0"
>
    <!-- DIRECTORIES -->
    <input dir="."/>

    <!-- INPUT PACKAGE FILTER -->
    <include-package name=".*"/>

    <!-- OUTPUT LISTENER -->
    <listener class="com.valtech.source.dependometer.ui.console.output.HtmlWriter" args="./results"/>
    <listener class="com.valtech.source.dependometer.ui.console.output.CsvWriter" args="./results/summary.csv"/>
    <listener class="com.valtech.source.dependometer.ui.console.output.DetailedCsvWriter" args="./results/summary-detailed.csv"/>
    <!-- configure the detail level via an additional argument: layer, subsystem, package, compilation-unit, type (default = compilation-unit) -->
    <listener class="com.valtech.source.dependometer.ui.console.output.ViolationReportCsvWriter" args="./results/violation-report.csv type"/>
    <!-- configure the detail level via an additional argument: layer, subsystem, package, compilation-unit, type (default = package) -->
    <listener class="com.valtech.source.dependometer.ui.console.output.CycleParticipationReportCsvWriter" args="./results/cycle-participation-report.csv type"/>
    <listener class="com.valtech.source.dependometer.ui.console.output.TypeDependencyCsvWriter" args="./results/typedependencies.csv"/>

	<!-- ASSERTIONS -->
	<assertion pattern="assert"/>
	
	<!-- SKIP -->
	<skip prefix="java\..*"/>

</project>

=== dheraclio/dependometer/dependometer-cpp-1.2.7/src/test/test-dependencies/assertions/dep.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE project SYSTEM "Configuration.dtd">

<!--
	name
		the project name appears in the reports
	numberOfCyclesFeedbackOnConsole (default = "1")
		Every time the configured number of cycles is reached you get an extra warning in your shell
	numberOfCycleAnalysisProgressFeedbackOnConsole (default = "1")
		Every time the remaining number of nodes was accordingly reduced you get an extra info in your shell
	checkLayerDependencies (default = "true")
	checkSubsystemDependencies (default = "true")
		"true"	all dependencies are checked against the allowed dependencies (depends-upon node)
		"false" no dependency check
	checkPackageDependencies (default = "true")
		"true" 	all package dependencies are checked against the allowed dependencies (only packages are checked that have a package description)
		"false" no dependency check
	cumulateLayerDependencies (default = "true")
	cumulateSubsystemDependencies (default = "true")
	cumulatePackageDependencies (default = "true")
	cumulateCompilationUnitDependencies (default = "true")
	cumulateTypeDependencies (default = "true")
		"true"	cumulate dependencies
		"false" no cumulation
	ingorePhysicalStructure (default = "false")
		"true"	physical structure will be ignored, only the logical structure will be used to build fully qualified name (To be used if physical structure == logical structure)
		"false" physical structure will be prepended to the logical structure to build fully qualified name
	maxLayerCycles (default = "0")
	maxSubsystemCycles (default = "0")
	maxPackageCycles (default = "0")
	maxCompilationUnitCycles (default = "0")
	maxTypeCycles (default = "0")
		Configure the cycle analysis behavior to avoid an endlessly running process. As an alternativ you can start the
		dependometer with the command 'java -jar dependomter.jar -file <your configuration>' and terminate the analyis when
		ever you want with 'ctrl-c' in the shell. This is possible past the point where in the shell the message 'Terminate
		running analysis with 'ctrl-c'!' appears. Past this point you have also a valid html output. Only the cycle analyis
		output gets updated. With a corresponding refresh in your browser you can see the updated information.
		"-2" 	no analysis
		"-1" 	cycle existence check
		"0"	like "-1" plus detailed cycle participation (which elements participate in cycles?) and levelization
		">0"	like 0" but with the provided upper limit for detected cycles (stops if 'n' cycles are reached)
-->
<project name="Assertions Test" ignorePhysicalStructure="false" maxPackageCycles="5000"  maxTypeCycles="5000" maxCompilationUnitCycles="5000">
	<!-- DIRECTORIES -->

	<input dir="."/>
    <system-include-path dir="."/>
	
	<system-define symbol="VAL" macro="VALTECH"/>

	<!-- INPUT PACKAGE FILTER -->
	<!-- include-package name=".*"/--> <!-- Include packages matching the given pattern ... - regular expressions JDK 1.4-->
	<include-package name=".*"/>

	<!--exclude-package name="default"/--> <!-- Exclude packages matching the given pattern ...  - regular expressions JDK 1.4-->

	<exclude-compilation-unit name=".*Wurstsuppe\\stdafx.cpp"/><!-- Exclude compilation units matching the given pattern ...  - regular expressions JDK 1.4-->

	<!--
	Optional node for vertical slice analysis
		checkDependencies (default = "true" - the 'checkSubsystemDependencies' attribute must also be set to "true")
			"true"	all subsystem dependencies are 'cumulated' for the corresponding vertical slices the violations are shown
			"false" no visualization of 'cumulated' violations
		maxCycles (default = "0")
			as above
		exclude-subsystem
			specify which subsystems are not used for the vertical slice analysis (i.e. exclude the technical ones, normally
			technically motivated vertical division of all layers is rare)
	-->
	<!--
	<vertical-slices>
		<exclude-subsystem name="user-interface::.*"/>
		<exclude-subsystem name="application-general::.*"/>
	</vertical-slices>
	-->
	<!-- OUTPUT LISTENER -->
   	<listener class="com.valtech.source.dependometer.ui.console.output.HtmlWriter" args="./results"/>
   	<listener class="com.valtech.source.dependometer.ui.console.output.CsvWriter" args="./results/summary.csv"/>
   	<listener class="com.valtech.source.dependometer.ui.console.output.DetailedCsvWriter" args="./results/summary-detailed.csv"/>
   	<!-- configure the detail level via an additional argument: layer, subsystem, package, compilation-unit, type (default = compilation-unit)-->
	<listener class="com.valtech.source.dependometer.ui.console.output.ViolationReportCsvWriter" args="./results/violation-report.csv type"/>
   	<!-- configure the detail level via an additional argument: layer, subsystem, package, compilation-unit, type (default = package)-->
	<listener class="com.valtech.source.dependometer.ui.console.output.CycleParticipationReportCsvWriter" args="./results/cycle-participation-report.csv type"/>
	<listener class="com.valtech.source.dependometer.ui.console.output.TypeDependencyCsvWriter" args="./results/typedependencies.csv"/>

	<!-- ASSERTIONS -->
	<assertion pattern="assert"/> <!-- Look for these assertion statements - regular expressions JDK 1.4-->

	<!-- IGNORE -->
	<!-- <ignore fromType=".*CycleTest.*" toType=".*CycleTest.*"/> --> <!-- Ignore matching type dependencies (Simulation) - regular expressions JDK 1.4-->

	<!-- SKIP -->
	<skip prefix="System.[a-zA-Z]*"/> <!-- Ignore the dependencies to external types - regular expressions JDK 1.4-->


	<!-- REFACTORINGS -->
	<!-- <refactor compilationUnit="com.valtech.source.dependometer.app.configprovider.filebased.xml.Refactoring" toPackage="com.valtech.source.dependometer.app.core.impl"/>--> <!-- Move compilation unit(s) to another package (Simulation) - n compilationUnits may be specified using the regular expressions from the JDK 1.4-->
	<!-- <refactor compilationUnit=".*Event" toPackage="com.valtech.source.dependometer.app.core.events"/>-->

	<!-- THRESHOLDS -->
	<lower-threshold name="Project.NumberOfProjectInternalLayers" value="1"/> <!-- Need at least one defined layer -->
	<lower-threshold name="Project.NumberOfDefinedLayerDependencies" value="1"/>
	<lower-threshold name="Project.NumberOfProjectInternalSubsystems" value="1"/>
	<lower-threshold name="Project.NumberOfDefinedSubsystemDependencies" value="1"/>
	<lower-threshold name="Project.PercentageOfLayersWithRcNotLessThanOne" value="100"/>
	<!-- lower-threshold name="Project.PercentageOfVerticalSlicesWithRcNotLessThanOne" value="100"/-->
	<lower-threshold name="Project.PercentageOfSubsystemsWithRcNotLessThanOne" value="100"/>
	<lower-threshold name="Project.PercentageOfPackagesWithRcNotLessThanOne" value="70"/>
	<lower-threshold name="Project.NumberOfDefinedPackageDependencies" value="0"/>
	<lower-threshold name="Project.AverageNumberOfAssertionsPerProjectInternalClass" value="5"/>
	<lower-threshold name="Project.NumberOfProjectInternalTypes" value="1"/> <!-- At least one type was matched by the package filter and therefore analyzed-->
	<upper-threshold name="Project.NumberOfProjectExternalSubsystems" value="5"/>
	<upper-threshold name="Project.NumberOfProjectExternalLayers" value="1"/>
	<upper-threshold name="Project.NumberOfNotImplementedSubsystems" value="0"/> <!-- All subsystems must have at least 1 assigned package -->
	<upper-threshold name="Project.ACD" value="13.65"/>
	<!-- upper-threshold name="Project.VerticalSliceCyclesExist" value="0"/-->
	<upper-threshold name="Project.LayerCyclesExist" value="0"/>
	<upper-threshold name="Project.SubsystemCyclesExist" value="0"/>
	<upper-threshold name="Project.PackageCyclesExist" value="0"/>
	<upper-threshold name="Project.MaxDepthOfPackageHierarchy" value="7"/>
	<upper-threshold name="Project.NumberOfProjectExternalPackages" value="7"/>
	<upper-threshold name="Project.NumberOfNotAssignedPackages" value="0"/>
	<upper-threshold name="Project.NumberOfForbiddenEfferentPackageDependencies" value="0"/>
	<upper-threshold name="Project.CompilationUnitCyclesExist" value="0"/>
	<upper-threshold name="Project.TypeCyclesExist" value="0"/>
	<upper-threshold name="Project.MaxDepthOfInheritance" value="5"/>

	<!-- LOGICAL ARCHITECTURE -->
	<layer name="TestLayer">
		<description>test layer</description>
		<subsystem name="TestSubsystem">
			<description>test subsystem</description>
       		<include-package name=".*"/>
       	</subsystem>
	</layer>
</project>

=== dheraclio/dependometer/dependometer-core-1.2.7/src/test/resources/metrics/architecture_dependencies-config.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE project SYSTEM "../Configuration.dtd">

<project name="Test" numberOfCyclesFeedbackOnConsole="1"
	numberOfCycleAnalysisProgressFeedbackOnConsole="1"
	checkLayerDependencies="true" checkSubsystemDependencies="true"
	checkPackageDependencies="true" cumulateLayerDependencies="true"
	cumulateSubsystemDependencies="true" cumulatePackageDependencies="true"
	cumulateCompilationUnitDependencies="true" cumulateTypeDependencies="true"
	maxLayerCycles="0" maxSubsystemCycles="0" maxPackageCycles="0"
	maxCompilationUnitCycles="0" maxTypeCycles="0">
	<input dir="." />
	<include-package name="application.*" />
	<include-package name="services.*" />
	<listener
		class="com.valtech.source.dependometer.ui.console.output.HtmlWriter"
		args="./results/dependometer" />

	<layer name="Application">
		<subsystem name="core">
			<include-package name="application.core.*" />
			<depends-upon name="Services::shopService"/>
		</subsystem>
		<depends-upon name="Services"/>
	</layer>

	<layer name="Services">
		<subsystem name="shopService">
			<include-package name="services" />
			<include-package name="services.shop" />
			<depends-upon name="Services::catalogueService"/>
		</subsystem>
		<subsystem name="catalogueService">
			<include-package name="services.catalogue" />
			<depends-upon name="Services::catalogueExportService"/>
		</subsystem>
		<subsystem name="catalogueExportService">
			<include-package name="services.catalogue.export" />
			<depends-upon name="External::extern1"/>
		</subsystem>
	</layer>

	<layer name="External">
		<subsystem name="extern1">
			<include-package name="external.sub1" />
		</subsystem>
	</layer>
</project>

=== dheraclio/dependometer/dependometer-core-1.2.7/src/test/resources/metrics/simple_architecture-config.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE project SYSTEM "../Configuration.dtd">

<project name="Test" numberOfCyclesFeedbackOnConsole="1"
	numberOfCycleAnalysisProgressFeedbackOnConsole="1"
	checkLayerDependencies="true" checkSubsystemDependencies="true"
	checkPackageDependencies="true" cumulateLayerDependencies="true"
	cumulateSubsystemDependencies="true" cumulatePackageDependencies="true"
	cumulateCompilationUnitDependencies="true" cumulateTypeDependencies="true"
	maxLayerCycles="0" maxSubsystemCycles="0" maxPackageCycles="0"
	maxCompilationUnitCycles="0" maxTypeCycles="0">
	<input dir="." />
	<include-package name="one.*" />
	<include-package name="two.*" />
	<listener
		class="com.valtech.source.dependometer.ui.console.output.HtmlWriter"
		args="./results/dependometer" />

	<!-- LOGICAL ARCHITECTURE -->
	<layer name="One">
		<description>Layer One</description>
		<subsystem name="system1">
			<description>system 1</description>
			<include-package name="one.*" />
		</subsystem>
	</layer>

	<layer name="Two">
		<description>Layer Two</description>
		<subsystem name="system2-1">
			<description>system 2-1</description>
			<include-package name="two" />
			<include-package name="two.sub1" />
		</subsystem>
		<subsystem name="system2-2">
			<description>system 2-2</description>
			<include-package name="two.sub2" />
		</subsystem>
		<subsystem name="system2-2-1">
			<description>system 2-2-1</description>
			<include-package name="two.sub2.subsub1" />
		</subsystem>
	</layer>

	<layer name="External">
		<subsystem name="extern1">
			<description>extern 1</description>
			<include-package name="external.sub1" />
		</subsystem>
	</layer>
</project>
